import 'package:flutter/material.dart';

class TaskFourListview extends StatefulWidget {
  const TaskFourListview({super.key});

  @override
  State<TaskFourListview> createState() => _TaskFourListviewState();
}

class _TaskFourListviewState extends State<TaskFourListview> {
  List<String> titles = [
    "1. Al-Fatihah",
    "2. Al-Baqarah",
    "3. Ali 'Imran",
    "4. An-Nisa'",
    "5. Al-Ma'idah",
    "6. Al-An'am",
    "7. Al-A'raf",
    "8. Al-Anfal",
    "9. At-Tawbah",
    "10. Yunus",
    "11. Hud",
    "12. Yusuf",
    "13. Ar-Ra'd",
    "14. Ibrahim",
    "15. Al-Hijr",
    "16. An-Nahl",
    "17. Al-Isra",
    "18. Al-Kahf",
    "19. Maryam",
    "20. Ta-Ha",
    "21. Al-Anbiya",
    "22. Al-Hajj",
    "23. Al-Mu’minun",
    "24. An-Nur",
    "25. Al-Furqan",
    "26. Ash-Shu'ara",
    "27. An-Naml",
    "28. Al-Qasas",
    "29. Al-Ankabut",
    "30. Ar-Rum",
    "31. Luqman",
    "32. As-Sajdah",
    "33. Al-Ahzab",
    "34. Saba",
    "35. Fatir",
    "36. Ya-Sin",
    "37. As-Saffat",
    "38. Sad",
    "39. Az-Zumar",
    "40. Ghafir",
    "41. Fussilat",
    "42. Ash-Shura",
    "43. Az-Zukhruf",
    "44. Ad-Dukhan",
    "45. Al-Jathiya",
    "46. Al-Ahqaf",
    "47. Muhammad",
    "48. Al-Fath",
    "49. Al-Hujurat",
    "50. Qaf",
    "51. Adh-Dhariyat",
    "52. At-Tur",
    "53. An-Najm",
    "54. Al-Qamar",
    "55. Ar-Rahman",
    "56. Al-Waqi'a",
    "57. Al-Hadid",
    "58. Al-Mujadila",
    "59. Al-Hashr",
    "60. Al-Mumtahina",
    "61. As-Saff",
    "62. Al-Jumu'a",
    "63. Al-Munafiqun",
    "64. At-Taghabun",
    "65. At-Talaq",
    "66. At-Tahrim",
    "67. Al-Mulk",
    "68. Al-Qalam",
    "69. Al-Haqqa",
    "70. Al-Ma'arij",
    "71. Nuh",
    "72. Al-Jinn",
    "73. Al-Muzzammil",
    "74. Al-Muddaththir",
    "75. Al-Qiyama",
    "76. Al-Insan",
    "77. Al-Mursalat",
    "78. An-Naba",
    "79. An-Nazi'at",
    "80. Abasa",
    "81. At-Takwir",
    "82. Al-Infitar",
    "83. Al-Mutaffifin",
    "84. Al-Inshiqaq",
    "85. Al-Buruj",
    "86. At-Tariq",
    "87. Al-A'la",
    "88. Al-Ghashiya",
    "89. Al-Fajr",
    "90. Al-Balad",
    "91. Ash-Shams",
    "92. Al-Lail",
    "93. Ad-Duhaa",
    "94. Al-Inshirah",
    "95. At-Tin",
    "96. Al-Alaq",
    "97. Al-Qadr",
    "98. Al-Bayyina",
    "99. Az-Zalzala",
    "100. Al-Adiyat",
    "101. Al-Qaria",
    "102. At-Takathur",
    "103. Al-Asr",
    "104. Al-Humaza",
    "105. Al-Fil",
    "106. Quraish",
    "107. Al-Ma'un",
    "108. Al-Kawthar",
    "109. Al-Kafiroon",
    "110. An-Nasr",
    "111. Al-Masad",
    "112. Al-Ikhlas",
    "113. Al-Falaq",
    "114. An-Nas"
  ];

  List<String> subtitles = [
    "Ayahs: 7, Ruku: 1, Makki",
    "Ayahs: 286, Ruku: 40, Madani",
    "Ayahs: 200, Ruku: 20, Madani",
    "Ayahs: 176, Ruku: 24, Madani",
    "Ayahs: 120, Ruku: 16, Madani",
    "Ayahs: 165, Ruku: 20, Makki",
    "Ayahs: 206, Ruku: 24, Makki",
    "Ayahs: 75, Ruku: 10, Madani",
    "Ayahs: 129, Ruku: 16, Madani",
    "Ayahs: 109, Ruku: 11, Makki",
    "Ayahs: 123, Ruku: 10, Makki",
    "Ayahs: 111, Ruku: 12, Makki",
    "Ayahs: 43, Ruku: 6, Madani",
    "Ayahs: 52, Ruku: 7, Makki",
    "Ayahs: 99, Ruku: 6, Makki",
    "Ayahs: 128, Ruku: 16, Makki",
    "Ayahs: 111, Ruku: 12, Makki",
    "Ayahs: 110, Ruku: 12, Makki",
    "Ayahs: 98, Ruku: 6, Makki",
    "Ayahs: 135, Ruku: 8, Makki",
    "Ayahs: 112, Ruku: 7, Makki",
    "Ayahs: 78, Ruku: 10, Madani",
    "Ayahs: 118, Ruku: 6, Makki",
    "Ayahs: 64, Ruku: 9, Madani",
    "Ayahs: 77, Ruku: 6, Makki",
    "Ayahs: 227, Ruku: 11, Makki",
    "Ayahs: 93, Ruku: 7, Makki",
    "Ayahs: 88, Ruku: 9, Makki",
    "Ayahs: 69, Ruku: 7, Makki",
    "Ayahs: 60, Ruku: 6, Makki",
    "Ayahs: 34, Ruku: 4, Makki",
    "Ayahs: 30, Ruku: 3, Makki",
    "Ayahs: 73, Ruku: 9, Madani",
    "Ayahs: 54, Ruku: 6, Makki",
    "Ayahs: 45, Ruku: 5, Makki",
    "Ayahs: 83, Ruku: 5, Makki",
    "Ayahs: 182, Ruku: 10, Makki",
    "Ayahs: 88, Ruku: 5, Makki",
    "Ayahs: 75, Ruku: 8, Makki",
    "Ayahs: 85, Ruku: 9, Makki",
    "Ayahs: 54, Ruku: 6, Makki",
    "Ayahs: 53, Ruku: 5, Makki",
    "Ayahs: 89, Ruku: 8, Makki",
    "Ayahs: 59, Ruku: 7, Makki",
    "Ayahs: 37, Ruku: 4, Makki",
    "Ayahs: 35, Ruku: 4, Makki",
    "Ayahs: 38, Ruku: 4, Makki",
    "Ayahs: 29, Ruku: 4, Madani",
    "Ayahs: 18, Ruku: 2, Madani",
    "Ayahs: 45, Ruku: 3, Makki",
    "Ayahs: 60, Ruku: 4, Makki",
    "Ayahs: 49, Ruku: 4, Makki",
    "Ayahs: 62, Ruku: 3, Makki",
    "Ayahs: 55, Ruku: 3, Madani",
    "Ayahs: 78, Ruku: 6, Makki",
    "Ayahs: 96, Ruku: 4, Madani",
    "Ayahs: 29, Ruku: 3, Madani",
    "Ayahs: 22, Ruku: 2, Madani",
    "Ayahs: 13, Ruku: 2, Madani",
    "Ayahs: 14, Ruku: 2, Madani",
    "Ayahs: 11, Ruku: 2, Madani",
    "Ayahs: 11, Ruku: 2, Madani",
    "Ayahs: 30, Ruku: 3, Makki",
    "Ayahs: 52, Ruku: 2, Makki",
    "Ayahs: 52, Ruku: 2, Makki",
    "Ayahs: 44, Ruku: 2, Makki",
    "Ayahs: 28, Ruku: 2, Makki",
    "Ayahs: 28, Ruku: 2, Makki",
    "Ayahs: 20, Ruku: 2, Makki",
    "Ayahs: 56, Ruku: 3, Makki",
    "Ayahs: 40, Ruku: 2, Makki",
    "Ayahs: 31, Ruku: 2, Makki",
    "Ayahs: 50, Ruku: 2, Makki",
    "Ayahs: 40, Ruku: 2, Makki",
    "Ayahs: 46, Ruku: 2, Makki",
    "Ayahs: 42, Ruku: 2, Makki",
    "Ayahs: 29, Ruku: 2, Makki",
    "Ayahs: 19, Ruku: 1, Makki",
    "Ayahs: 36, Ruku: 2, Makki",
    "Ayahs: 25, Ruku: 2, Makki",
    "Ayahs: 22, Ruku: 2, Makki",
    "Ayahs: 17, Ruku: 1, Makki",
    "Ayahs: 19, Ruku: 1, Makki",
    "Ayahs: 26, Ruku: 2, Makki",
    "Ayahs: 30, Ruku: 2, Makki",
    "Ayahs: 20, Ruku: 1, Makki",
    "Ayahs: 15, Ruku: 1, Makki",
    "Ayahs: 21, Ruku: 1, Makki",
    "Ayahs: 11, Ruku: 1, Makki",
    "Ayahs: 8, Ruku: 1, Makki",
    "Ayahs: 8, Ruku: 1, Makki",
    "Ayahs: 19, Ruku: 1, Makki",
    "Ayahs: 5, Ruku: 1, Makki",
    "Ayahs: 4, Ruku: 1, Makki",
    "Ayahs: 7, Ruku: 1, Makki",
    "Ayahs: 3, Ruku: 1, Makki",
    "Ayahs: 6, Ruku: 1, Makki",
    "Ayahs: 3, Ruku: 1, Makki",
    "Ayahs: 5, Ruku: 1, Makki",
    "Ayahs: 4, Ruku: 1, Makki",
    "Ayahs: 5, Ruku: 1, Makki",
    "Ayahs: 6, Ruku: 1, Makki"
  ];

  List<String> surahListArabic = [
    "ٱلْفَاتِحَةُ",
    "ٱلْبَقَرَةُ",
    "آلِ عِمْرَانَ",
    "ٱلنِّسَاءُ",
    "ٱلْمَائِدَةُ",
    "ٱلْأَنْعَامُ",
    "ٱلْأَعْرَافُ",
    "ٱلْأَنْفَالُ",
    "ٱلتَّوْبَةُ",
    "يُونُسُ",
    "هُودٌ",
    "يُوسُفُ",
    "ٱلرَّعْدُ",
    "إِبْرَاهِيمُ",
    "ٱلْحِجْرُ",
    "ٱلنَّحْلُ",
    "ٱلْإِسْرَاءُ",
    "ٱلْكَهْفُ",
    "مَرْيَمُ",
    "طه",
    "ٱلْأَنْبِيَاءُ",
    "ٱلْحَجُّ",
    "ٱلْمُؤْمِنُونَ",
    "ٱلنُّورُ",
    "ٱلْفُرْقَانُ",
    "ٱلشُّعَرَاءُ",
    "ٱلنَّمْلُ",
    "ٱلْقَصَصُ",
    "ٱلْعَنْكَبُوتُ",
    "ٱلرُّومُ",
    "لُقْمَانُ",
    "ٱلسَّجْدَةُ",
    "ٱلْأَحْزَابُ",
    "سَبَأٌ",
    "فَاطِرٌ",
    "يس",
    "ٱلصَّافَّاتُ",
    "ص",
    "ٱلزُّمَرُ",
    "غَافِرٌ",
    "فُصِّلَتْ",
    "ٱلشُّورَىٰ",
    "ٱلْزُّخْرُفُ",
    "ٱلدُّخَانُ",
    "ٱلْجَاثِيَةُ",
    "ٱلْأَحْقَافُ",
    "مُحَمَّدٌ",
    "ٱلْفَتْحُ",
    "ٱلْحُجُرَاتُ",
    "ق",
    "ٱلذَّارِيَاتُ",
    "ٱلطُّورُ",
    "ٱلنَّجْمُ",
    "ٱلْقَمَرُ",
    "ٱلرَّحْمَٰنُ",
    "ٱلْوَاقِعَةُ",
    "ٱلْحَدِيدُ",
    "ٱلْمُجَادِلَةُ",
    "ٱلْحَشْرُ",
    "ٱلْمُمْتَحَنَةُ",
    "ٱلصَّفُّ",
    "ٱلْجُمُعَةُ",
    "ٱلْمُنَافِقُونَ",
    "ٱلتَّغَابُنُ",
    "ٱلطَّلَاقُ",
    "ٱلتَّحْرِيمُ",
    "ٱلْمُلْكُ",
    "ٱلْقَلَمُ",
    "ٱلْحَاقَّةُ",
    "ٱلْمَعَارِجُ",
    "نُوحٌ",
    "ٱلْجِنُّ",
    "ٱلْمُزَّمِّلُ",
    "ٱلْمُدَّثِّرُ",
    "ٱلْقِيَامَةُ",
    "ٱلْإِنْسَانُ",
    "ٱلْمُرْسَلَاتُ",
    "ٱلنَّبَأُ",
    "ٱلنَّازِعَاتُ",
    "عَبَسَ",
    "ٱلتَّكْوِيرُ",
    "ٱلِانْفِطَارُ",
    "ٱلْمُطَفِّفِينَ",
    "ٱلِانْشِقَاقُ",
    "ٱلْبُرُوجُ",
    "ٱلطَّارِقُ",
    "ٱلْأَعْلَىٰ",
    "ٱلْغَاشِيَةُ",
    "ٱلْفَجْرُ",
    "ٱلْبَلَدُ",
    "ٱلشَّمْسُ",
    "ٱللَّيْلُ",
    "ٱلضُّحَىٰ",
    "ٱلشَّرْحُ",
    "ٱلتِّينُ",
    "ٱلْعَلَقُ",
    "ٱلْقَدْرُ",
    "ٱلْبَيِّنَةُ",
    "ٱلزَّلْزَلَةُ",
    "ٱلْعَادِيَاتُ",
    "ٱلْقَارِعَةُ",
    "ٱلتَّكَاثُرُ",
    "ٱلْعَصْرُ",
    "ٱلْهُمَزَةُ",
    "ٱلْفِيلُ",
    "قُرَيْشٌ",
    "ٱلْمَاعُونُ",
    "ٱلْكَوْثَرُ",
    "ٱلْكَافِرُونَ",
    "ٱلنَّصْرُ",
    "ٱلْمَسَدُ",
    "ٱلْإِخْلَاصُ",
    "ٱلْفَلَقُ",
    "ٱلنَّاسُ"
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
          title: Center(
            child: Text(
              "Surah List",
              style: TextStyle(
                  fontSize: 20,
                  fontWeight: FontWeight.bold,
                  color: Colors.yellow),
            ),
          ),
          backgroundColor: Colors.deepOrangeAccent),
      body: ListView.builder(
          scrollDirection: Axis.vertical,
          physics: BouncingScrollPhysics(),
          itemCount: titles.length < subtitles.length
              ? titles.length
              : subtitles.length < surahListArabic.length
                  ? subtitles.length
                  : surahListArabic.length,
          itemBuilder: (context, int index) {
            return Card(
              color: Colors.greenAccent,
              elevation: 5,
              child: ListTile(
                title: Text(titles[index],
                    style:
                        TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
                subtitle: Text(subtitles[index]),
                leading: Icon(Icons.menu_book, size: 40, color: Colors.black),
                trailing: Text(
                  surahListArabic[index],
                  style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
                ),
              ),
            );
            
          },

    ));
  }
}
